dbt_bugs:
  outputs:
    dev:
      dbname: postgres
      host: localhost
      pass: root
      port: 5432
      schema: public
      threads: 1
      type: postgres
      user: postgres
  target: dev
